
imagePullSecrets: []

proxy:
  image:
    repository: gcr.io/kubebuilder/kube-rbac-proxy
    pullPolicy: IfNotPresent
    tag: "v0.5.0"
manager:
  image:
    repository: localhost:5000/ipam
    pullPolicy: IfNotPresent
    tag: "latest"
  resources:
    limits:
      cpu: 100m
      memory: 30Mi
    requests:
      cpu: 100m
      memory: 20Mi
  securityContext:
    allowPrivilegeEscalation: false

podAnnotations: {}

podSecurityContext:
  runAsUser: 65532

replicaCount: 1

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

metricsService:
  type: ClusterIP
  port: 8443

webhookService:
  type: ClusterIP
  port: 443

cluster:
  domain: cluster.local

crd:
  group: ipam.onmetal.de
  plural: ipams
  singular: ipam
  kind: Ipam
  listKind: IpamList
  scope: Namespaced
