
imagePullSecrets: []

proxy:
  image:
    repository: gcr.io/kubebuilder/kube-rbac-proxy
    pullPolicy: IfNotPresent
    tag: "v0.5.0"
manager:
  image:
    repository: localhost:5000/onmetal/ipam
    pullPolicy: IfNotPresent
    tag: "latest"
  resources:
    limits:
      cpu: 100m
      memory: 30Mi
    requests:
      cpu: 100m
      memory: 20Mi
  securityContext:
    allowPrivilegeEscalation: false

podAnnotations: {}

podSecurityContext:
  runAsUser: 65532

replicaCount: 1

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

metricsService:
  type: ClusterIP
  port: 8443

webhookService:
  type: ClusterIP
  port: 443

cluster:
  domain: cluster.local

crd:
  ipam:
    group: ipam.onmetal.de
    plural: ipams
    singular: ipam
    kind: Ipam
    listKind: IpamList
    scope: Namespaced
  ng:
    group: ipam.onmetal.de
    plural: networkglobals
    singular: networkglobal
    kind: NetworkGlobal
    listKind: NetworkGlobalList
    scope: Namespaced
  subnet:
    group: ipam.onmetal.de
    plural: subnets
    singular: subnet
    kind: Subnet
    listKind: SubnetList
    scope: Namespaced
  example:
    group: ipam.onmetal.de
    plural: examples
    singular: example
    kind: Example
    listKind: ExampleList
    scope: Namespaced


leaderElection:
  leaderElect: true
  resourceName: f42c18d5.onmetal.de