apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "chart.fullname" . }}-manager-role
  labels:
  {{- include "chart.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - {{ .Values.crd.ipam.group }}
    resources:
      - {{ .Values.crd.ipam.plural }}
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - {{ .Values.crd.ipam.group }}
    resources:
      - {{ .Values.crd.ipam.plural }}/finalizers
    verbs:
      - update
  - apiGroups:
      - {{ .Values.crd.ipam.group }}
    resources:
      - {{ .Values.crd.ipam.plural }}/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - {{ .Values.crd.ng.group }}
    resources:
      - {{ .Values.crd.ng.plural }}
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - {{ .Values.crd.ng.group }}
    resources:
      - {{ .Values.crd.ng.plural }}/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - {{ .Values.crd.subnet.group }}
    resources:
      - {{ .Values.crd.subnet.plural }}
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - {{ .Values.crd.subnet.group }}
    resources:
      - {{ .Values.crd.subnet.plural }}/finalizers
    verbs:
      - update
  - apiGroups:
      - {{ .Values.crd.subnet.group }}
    resources:
      - {{ .Values.crd.subnet.plural }}/status
    verbs:
      - get
      - patch
      - update
