apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "chart.fullname" . }}-manager-role
  labels:
  {{- include "chart.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - {{ .Values.crd.ip.group }}
    resources:
      - {{ .Values.crd.ip.plural }}
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - {{ .Values.crd.ip.group }}
    resources:
      - {{ .Values.crd.ip.plural }}/finalizers
    verbs:
      - update
  - apiGroups:
      - {{ .Values.crd.ip.group }}
    resources:
      - {{ .Values.crd.ip.plural }}/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - {{ .Values.crd.subnet.group }}
    resources:
      - {{ .Values.crd.subnet.plural }}
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - {{ .Values.crd.subnet.group }}
    resources:
      - {{ .Values.crd.subnet.plural }}/finalizers
    verbs:
      - update
  - apiGroups:
      - {{ .Values.crd.subnet.group }}
    resources:
      - {{ .Values.crd.subnet.plural }}/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - {{ .Values.crd.networkcounter.group }}
    resources:
      - {{ .Values.crd.networkcounter.plural }}
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - {{ .Values.crd.networkcounter.group }}
    resources:
      - {{ .Values.crd.networkcounter.plural }}/finalizers
    verbs:
      - update
  - apiGroups:
      - {{ .Values.crd.networkcounter.group }}
    resources:
      - {{ .Values.crd.networkcounter.plural }}/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - {{ .Values.crd.network.group }}
    resources:
      - {{ .Values.crd.network.plural }}
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - {{ .Values.crd.network.group }}
    resources:
      - {{ .Values.crd.network.plural }}/finalizers
    verbs:
      - update
  - apiGroups:
      - {{ .Values.crd.network.group }}
    resources:
      - {{ .Values.crd.network.plural }}/status
    verbs:
      - get
      - patch
      - update