apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-manager-metrics-service
  labels:
    control-plane: {{ include "chart.fullname" . }}-controller-manager
  {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metricsService.type }}
  ports:
    - name: https
      port: {{ .Values.metricsService.port }}
      targetPort: https
  selector:
    control-plane: controller-manager
  {{- include "chart.selectorLabels" . | nindent 4 }}
