# permissions for end users to edit examples.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: example-editor-role
rules:
- apiGroups:
  - ipam.onmetal.de
  resources:
  - examples
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ipam.onmetal.de
  resources:
  - examples/status
  verbs:
  - get
