# permissions for end users to edit ipams.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ipam-editor-role
rules:
- apiGroups:
  - ipam.onmetal.de
  resources:
  - ipams
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ipam.onmetal.de
  resources:
  - ipams/status
  verbs:
  - get
