
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - machine.onmetal.de
  resources:
  - networkglobals
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - machine.onmetal.de
  resources:
  - networkglobals/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - machine.onmetal.de
  resources:
  - subnets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - machine.onmetal.de
  resources:
  - subnets/finalizers
  verbs:
  - update
- apiGroups:
  - machine.onmetal.de
  resources:
  - subnets/status
  verbs:
  - get
  - patch
  - update
