apiVersion: ipam.onmetal.de/v1alpha1
kind: Subnet
metadata:
  name: subnet-sample
spec:
  cidr: "10.0.0.0/8"
  parentSubnetName: ""
  networkGlobalName: networkglobal-sample
  regions:
    - euw
  availabilityZones:
    - a
    - b
    - c