apiVersion: ipam.onmetal.de/v1alpha1
kind: Subnet
metadata:
  name: ipv6-parent-cidr-subnet-sample
spec:
  cidr: "fd34:5d8f:e75e:f3a2::/64"
  networkName: network-sample
  regions:
    - euw
  availabilityZones:
    - a
    - b
    - c