apiVersion: ipam.onmetal.de/v1alpha1
kind: Ip
metadata:
  name: ipv6-resource-ip-sample
spec:
  subnetName: ipv6-child-cidr-subnet-sample
  resourceReference:
    apiVersion: ipam.onmetal.de/v1alpha1
    kind: NetworkCounter
    name: referred-networkcounter-sample
